#!/bin/bash

#possible arguments
#space, left, right

backupID=$( xdotool getactivewindow )
echo $backupID

destinationID=$( xdotool search --onlyvisible --name 'VICE (C64)' )
echo $destinationID

if [[ "$#" -eq 1 ]]; then
	#focusing into youtube
	xdotool windowactivate $destinationID

	#sleep for little
	sleep 0.05

	echo one argument!
	
	case "$1" in
		#cut) scrot -s /home/a/Obrazy/Wyklady/ICZKOM/wyk.png ;;
		widow)scrot -s /home/a/Dokumenty/Sprawozdania/Gry\ mobilne\ -\ projekt/scrots ;;
		#cut) scrot -s /home/a/Obrazy/Wyklady/PAI/wyk.png ;;
		#window) scrot -u /home/a/Obrazy/Wyklady/ICZKOM/wyk.png ;;
		#window) scrot -u /home/a/Obrazy/Wyklady/PAI/wyk.png ;;
		default) echo undefined key pressed!;;
	esac

	#going back to previous window
	#xdotool windowactivate $backupID
fi

#xdotool windowactivate `xdotool search --onlyvisible --name 'youtube'`
